<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://r0743641.eu.qlikcloud.com/resources/autogenerated/qlik-styles.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">


    <title>Project2D</title>
</head>
<body class="normal_body" >
{{--  Navigation  --}}

@include('shared.navigation')
<div id="body">


<main class="container size mt-3">

    @yield('main', 'Page under construction ...')
</main>
</div>
{{--  Footer  --}}
@include('shared.footer')

<script src="{{ mix('js/app.js') }}"></script>
<script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js></script>
<script type="text/javascript" src="jquery.dataTables.js"></script>
<script type="text/javascript" src="https://r0743641.eu.qlikcloud.com/resources/assets/external/requirejs/require.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js%22%3E"></script>

@yield('script_after')
</body>
</html>
