<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

{{--    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">--}}
    <link rel="stylesheet" href="https://r0743641.eu.qlikcloud.com/resources/autogenerated/qlik-styles.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    <title>Project2D</title>
</head>
<body class="normal_body" >
{{--  Navigation  --}}

@include('shared.navigation')
<div id="body">


<main class="container size mt-3">

    @yield('main', 'Page under construction ...')
</main>
</div>
{{--  Footer  --}}
@include('shared.footer')
<script type="text/javascript" src="https://r0743641.eu.qlikcloud.com/resources/assets/external/requirejs/require.js"></script>
<script src="{{ mix('js/app.js') }}"></script>
<script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js></script>
<script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js></script>

{{--<script type="text/javascript" src="https://r0743641.eu.qlikcloud.com/resources/assets/external/requirejs/require.js"></script>--}}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js%22%3E"></script>
@auth
    @if(auth()->user()->isAdmin or auth()->user()->isReceptionist or auth()->user()->isChauffeur){
    <script>
    /*
 * Basic responsive mashup template
 * @owner Enter you name here (xxx)
 */
    /*
     *    Fill in host and port for Qlik engine
     */


    connect();

    async function connect() {
        const urlQlikServer = "https://r0743641.eu.qlikcloud.com/";
        const urlLoggedIn = "api/v1/audits";//Use GET request to see if you are authenticated
        const urlLogin = "login";
        const webIntegrationId = 'Fyml_Ta_M3TY9YBzn0n2TCNaeykh5SK5';

        //Check to see if logged in
        return await fetch(`${urlQlikServer}${urlLoggedIn}`, {
            credentials: 'include',
            headers: {
                'Qlik-Web-Integration-ID':webIntegrationId
            }
        })
            .then(async function(response)
            {
                //check if user is authenticated; if not, redirect to login page
                if(response.status===401){
                    const url = new URL(`${urlQlikServer}login`);
                    url.searchParams.append('returnto', 'http://projectd2.westeurope.cloudapp.azure.com');
                    url.searchParams.append('qlik-web-integration-id', webIntegrationId);
                    window.location.href = url;
                }
            })
            .catch(function(error)
            {
                console.error(error);
            });
    }

    var config1 = {
        host: "r0743641.eu.qlikcloud.com", //the address of your Qlik Engine Instance
        prefix: "/", //or the virtual proxy to be used. for example "/anonymous/"
        port: 443, //or the port to be used if different from the default port
        isSecure: true, //should be true if connecting over HTTPS
        webIntegrationId: 'Fyml_Ta_M3TY9YBzn0n2TCNaeykh5SK5' //only needed in SaaS editions and QSEoK
    };

    require.config( {
        baseUrl: (config1.isSecure ? "https://" : "http://" ) + config1.host + (config1.port ? ":" + config1.port : "") + config1.prefix + "resources",
        webIntegrationId: config1.webIntegrationId
    } );

    require( ["js/qlik"], function ( qlik ) {
        console.log('qlik', qlik);
        qlik.on( "error", function ( error ) {
            $( '#popupText' ).append( error.message + "<br>" );
            $( '#popup' ).fadeIn( 1000 );
        } );
        $( "#closePopup" ).click( function () {
            $( '#popup' ).hide();
        } );


        //opend corona app
        var app = qlik.openApp("8a89b99d-1827-43ca-9b85-adb4ce8cd5d5", config1);

        //gemiddelde tijd in het bedrijf
        app.getObject('QV01', 'qdrKKC');
        //map Toeristen vs map besmettingen
        app.getObject('QV02', 'XPRUT');



        //clear all functie werkt niet omdat ik met verschillende alternet states heb
        $("#clearAll").click(function() {
            app.clearAll(true);


        });
        //geeft een lijst weer met alle qlik themas die je hebt
        //qlik.getThemeList().then(function(list){ var str = ""; list.forEach(function(value) { str += value.name + '(' + value.id + ")\n"; }); alert(str); });
        //applyd het genoemde thema en past het toe op de webpagina
        qlik.theme.apply('project4.0').then(function(result){
            //alert('theme applied with result: ' + result);
        });
        //laat zien welk thema er op de html pagina gebruikt word
        /*   app.theme.getApplied().then(function(qtheme){
           alert('Current theme background color: ' + qtheme.id);

           });*/
    } );

</script>
        @endif

@endauth
@yield('script_after')
@if(env('APP_DEBUG'))
    <script>
        $('form').attr('novalidate', 'true');
    </script>
@endif

</body>
</html>
